### ISSUE TITLE
compile failure

### ISSUE THREAD

**Issue by LeoChanW** [gt1/daccord#1]
HI，there are some problems when I compile daccord.
（./configure --with-libmaus2=${LIBMAUSPREFIX} \
	--prefix=${HOME}/daccord）
######################
checking for pkg-config... /usr/bin/pkg-config
checking pkg-config is at least version 0.9.0... yes
checking for ANSI C header files... (cached) yes
checking for libmaus2... no
configure: error: Package requirements (libmaus2 >= 2.0.303) were not met:

No package 'libmaus2' found

Consider adjusting the PKG_CONFIG_PATH environment variable if you
installed software in a non-standard prefix.

Alternatively, you may set the environment variables libmaus2_CFLAGS
and libmaus2_LIBS to avoid the need to call pkg-config.
See the pkg-config man page for more details.

##########################
'libmaus2' has been 
libtoolize
aclocal
autoreconf -i -f
./configure
make

How should I configure the path of libmaus2?
Thanks a lot

**Comment by gt1** [comment]
Hi,

did you set the environment variable LIBMAUSPREFIX to a value?

What is the output of

set | grep LIBMAUSPREFIX

?

**Comment by LeoChanW** [comment]
Output ：
set | grep LIBMAUSPREFIX
LIBMAUSPREFIX=/home/chw/libmaus2-2.0.338-release-20170512104458/src/libmaus2/

**Comment by gt1** [comment]
This looks like you set LIBMAUSPREFIX to the libmaus2 source folder. You need to point it to and installed version of libmaus2.

Try installing libmaus2 with something like

./configure --prefix=$HOME/libmaus2
make clean
make install
export LIBMAUSPREFIX=$HOME/libmaus2
