### ISSUE TITLE
Split_Agr not really splitting.

### ISSUE THREAD

**Issue by PhilippBongartz** [gt1/daccord#10]
I have now tested your pipeline on a transposon dataset with 6 copies. Everything runs smoothly, but the final result of Split_Agr doesn't seem to disambiguate the reads. The final overlap file is still almost as large as the initial one. 

I assume that this is user error, these repeats should be resolvable. 
I used the following flags:
./daccord -V0 -t4 -D500
./split_agr -d35

I just realised that the coverage is probably significantly higher for this data set (around 50). Can that be a reason for the bad result? Also, some of the alignments are broken, which doesn't seem ideal, because there are likely differences where the alignment breaks, is there a flag to force global alignment? 

Thank you for your time, any help would be appreciated.

**Comment by gt1** [comment]
split_agr is not really suitable copy numbers larger than 2 or 3 (this is described in the paper on Biorxiv). split_dis can be used for this, but it is rather slow due to it's complexity. It would suggest to limit the depth to 20 to get a tolerable run-time behaviour. Alignments in pieces instead of continuous should not be a problem. The tools are implemented to take this into account as it is so common in long reads.

Out of curiosity: what amount of difference do you expect to see between the copies?

**Comment by PhilippBongartz** [comment]
Ah, ok, then I mixed the two up. I'll try split_dis. 

When you say depth, do you mean sequencing depth -d? Or do you mean the maximum number of alignments -D. 

The alignment in pieces might be a problem, if the differences between copies are the reason for the alignment break and therefore not part of the alignment. But if you say that this is not a problem, I'll trust on that. 

The only hard number I have right now is that in this dataset between each pair of copies there are at least 10 differences. But probably a couple of dozens or so, minimum.

**Comment by PhilippBongartz** [comment]
I now tried split_dis and experience the opposite problem:

I used -d20 as well as -d50 to calculate the split for the first ten reads (-I0,10). In both cases the resulting overlap file is empty. There are several phase_array-files and phase_drop_array-files, one of which seems to contain something, the other have a size of zero bytes.

This is the output. I wonder about the DC[365]=92298 4219. 
....
DC[364]=0 3245
DC[365]=92298 4219
DC[366]=0 3577
DC[367]=0 3523
DC[368]=123 4259
DC[369]=0 3917
DC[370]=0 3913
DC[371]=0 3922
[V] keep 10 
[V] drop 10 0;1;2(2);3;4;5;6;7;8;9;11;12;13;14;15;16;17;18;19;20;21;22(2);23;24;25;26;27;28(2);29;30;31;32;33(2);34;35;36;37;38(2);39;40;41;42;43;44(2);45;46(2);47;48(2);49;50(2);51;52;53;54;55;56;57(2);58;59(2);60;61(2);62(3);63(2);64;65;66(2);67;68;69;70(2);71;72(2);73;74;75;76;77;78(2);79;80;81;82;83;84;85;86(2);87;88;89;90;91;92;93;94(2);95;96(3);97;98;99;100(2);101;102;103;104;105(3);106;107;108(3);109(2);110;111;112(2);113(2);114;115;116(2);117(2);118;119;120;121(2);122(2);123;124;125;126;127;128;129;130;131;132;133(2);134;135;136(2);137;138;139;140;141(2);142;143;144;145;146;147;148;149(3);150;151;152;153;154;155;156;157;158;159(2);160(3);161;162;163(2);164;165;166(2);167(2);168(2);169;170;171(2);172;173(2);174(2);175;176;177(2);178;179;180;181;182;183(2);184(2);185(2);186;187;188(2);189;190(2);191;192;193;194;195;196;197;198;199(2);200;201;202(2);203;204;205(2);206;207(2);208;209;210;211(2);212(2);213;214;215(2);216;217;218;219;220;221;222;223(2);224;225;226;227;228;229(2);230(2);231;232;233;234;235;236;237;238;239;240(2);241;242;243;244;245;246;247;248;249(2);250;251;252;253;254(2);255;256;257;258(2);259;260;261;262;263(2);264;265(3);266;267;268;269;270(2);271;272;273;274(2);275(2);276(2);277;278;279;280;281;282(2);283;284;285(2);286;287;288;289;290;291;292;293;294(2);295;296;297;298(2);299(2);300;301(2);302;303(2);304;305;306;307(2);308;309;310(2);311;312(2);313;314;315;316;317;318(2);319;320;321(2);322(2);323(2);324(2);325;326;327(2);328;329(2);330;331;332;333;334;335;336;337;338;339;340;341;342;343(2);344(2);345(2);346(2);347;348;349;350;351;352;353;354;355;356(2);357(2);358(2);
[V] read id 10 time 07:37:99624999
[V] accumulated time 3572.3
[V] processing time 59:32:29899500

**Comment by gt1** [comment]
Could you let me know what the program outputs as dcthres? (there should be a line saying using dcthres=)

**Comment by PhilippBongartz** [comment]
[V] using dcthres=0

**Comment by gt1** [comment]
Thanks. Apparently the computation of this parameter (called h_t in the paper) went wrong for some reason. Would you be able to post the complete log prefix? (before any [V] read id lines appear)

**Comment by PhilippBongartz** [comment]
[V] args[0]=/Users/Phille/daccord/bin/split_dis
[V] args[1]=-d20
[V] args[2]=-I0\05410
[V] args[3]=MidTransposonMMA_6SplitDis.las
[V] args[4]=MidTransposonMMA_6_daccord_consensus.fasta
[V] args[5]=MidTransposonMMA_6.las
[V] args[6]=/Users/Phille/Desktop/NewRepeatResolver/TransposonMSA/MidTransposonMMA_6.db
[V] AlignmentStatistics(matches=172714946,mismatches=2847783,insertions=12399559,deletions=6265025,editdistance=21512367,erate=0.1107587119)
[V] p=0.889241
[V] p^2=0.79075
[V] drate=0.01
[V] checkdisagreement=0
[V] d=20
[V] dthres=11
[V] copying .MidTransposonMMA_6.las.bidx to mem:.input.las.bidx...done.
[V] copying .MidTransposonMMA_6.las.idx to mem:.input.las.idx...done.
[V] minaread=0 toparead=11
[V] copying /Users/Phille/Desktop/NewRepeatResolver/TransposonMSA/MidTransposonMMA_6.db to memory...done.
[V] avgreadlen=4449.63
[V] P.first=0
[V] d'=2
[V] (d' 2)( ((kv-1) d') 2)=0
[V] using dcthres=0
[S] handling aread 0
[V] chainid=0/380
[V] chainid=1/380
[V] chainid=2/380
[V] chainid=3/380
...

**Comment by gt1** [comment]
Your average read length is unexpectedly small for current long read sequencing. Is this due to your specific application in transposon analysis?

Anyway, here is why the splitting does not work in this run:

split_dis first computes an arrival rate a from the parameters given, which is avgreadlen / d = 223 .  The programs default setting is not to try splitting on regions smaller than phasethres=4000bp (this can be set using the -p parameter). The number of reads spanning phasethres bases on any read is expected to be (avgreadlen - phasethres)/a which is d'=2 in the case above, so quite low. The program then tries to avoid missing cases with lower than average depth probability (it only excludes the bottom 1%), so it lowers the required depth from d'=2 to P.first=0 and derives the parameter called h_t from this, which due to P.first=0 ends up being zero. In consequence it will a set of reads to be different if they have at least zero of the tuples mentioned in the paper, which obviously is not a good idea.

You could either try running the splitting on  a subset of the reads which is longer on average (if this is possible this is what I would suggest), or try to lower the phase threshold by setting the -p parameter to something smaller than 4000 so dcthres will end up being something larger than zero. Lowering the phase threshold may have other negative side effects though.

**Comment by PhilippBongartz** [comment]
The reason why the reads are relatively short, is that I cut away the unique flanking sequences. Otherwise the tool would just seize on the flanking sequences to distinguish the reads, while I'm interested in how well it distinguishes the repeat regions. 

Almost all of my transposon test sets have longer sequences than that. But for all of them the arrival rate calculated wouldn't have anything to do with the actual read properties, because they all contain spanning reads where the unique flanking sequences have been cut away. Will that be a problem? And if yes, is there a way to work around it? Maybe I could just manually set d'=d in the code?

**Comment by gt1** [comment]
Yes, you could try setting d'=d assuming that most reads actually span the regions you are interested in.

**Comment by PhilippBongartz** [comment]
I set d'=d, but now we're back at retaining all overlaps. Any thoughts? Otherwise I'll try to force global alignments with -e.50, maybe that'll help.

[V] args[0]=/Users/Phille/daccord/bin/split_dis
[V] args[1]=-d20
[V] args[2]=-I0\05410
[V] args[3]=MidTransposonMMA_6SplitDis.las
[V] args[4]=MidTransposonMMA_6_daccord_consensus.fasta
[V] args[5]=MidTransposonMMA_6.las
[V] args[6]=/Users/Phille/Desktop/NewRepeatResolver/TransposonMSA/MidTransposonMMA_6.db
[V] AlignmentStatistics(matches=172714946,mismatches=2847783,insertions=12399559,deletions=6265025,editdistance=21512367,erate=0.1107587119)
[V] p=0.889241
[V] p^2=0.79075
[V] drate=0.01
[V] checkdisagreement=0
[V] d=20
[V] dthres=11
[V] copying .MidTransposonMMA_6.las.bidx to mem:.input.las.bidx...done.
[V] copying .MidTransposonMMA_6.las.idx to mem:.input.las.idx...done.
[V] minaread=0 toparead=11
[V] copying /Users/Phille/Desktop/NewRepeatResolver/TransposonMSA/MidTransposonMMA_6.db to memory...done.
[V] avgreadlen=4449.63
[V] P.first=10
[V] d'=20
[V] (d' 2)( ((kv-1) d') 2)=2025
[V] using dcthres=2025
[S] handling aread 0
[V] chainid=0/380
[V] chainid=1/380
...

**Comment by gt1** [comment]
I don't think daligner supports -e.5 , could you provide the new log for a read? I'm also curious about the zero byte files mentioned above. Valid LAS files are never zero bytes, even when they contain no overlaps.

**Comment by PhilippBongartz** [comment]
It's not the LAS files that had zero bytes, that was the phase_array-files and phase_drop_array-files. 

Here is the final output of a different transposon data set. This one looks a little better, I think the number of overlaps is reduced to a quarter of the original overlaps. In fact, if I filter them again with a minimal collective overlap length threshold, this might contain actual resolution. I'll do that tomorrow, than I'll get back to you.

...
DC[373]=409543 6329
DC[374]=0 3067
DC[375]=0 1086
DC[376]=1673331 4471
DC[377]=0 1086
DC[378]=239214 5368
[V] keep 10 0;1;2;3;6;7(2);8(3);9;12;13;18;22;23;24(2);26;27;29;35;36;37;38(3);41;45;46;47;50;52;53;54;55;56;60;61;62;63;65;68;69;70;72;75;76;77;78;79;80;81;83;84;90;93;94;95;96;98;103;105;108;109(3);114;124;125;126;128;129;130;131;132;133;134;138(3);139;144;145;147;148;150;152(3);153(3);155(3);157;160(3);163;164;165;167;170(3);174(3);177;179;180;181(4);184;185;187;188(3);189;190;191;192;198;203;206;207;209;211;212;214;215(3);217;219;220;223;225;226;227(2);230;232;233;234;237;245;249(3);250;252;254(3);255;
[V] drop 10 0(2);1(2);2(2);3(2);4(3);5(2);6(2);9(2);11;12(2);13(2);14;15;16;17;18(2);19;20;21;22(2);23(2);25;26(2);27(2);28(2);29(2);30;31;32;33;34;35(2);36(2);37(2);39(2);40;41(2);42;43;44(2);45(2);46(2);47(3);48;49;50(2);51;52(2);53(2);54(2);55(2);56(2);57(2);58;59;60(2);61(2);63(2);64;65(2);66;67;68(2);69(2);70(2);71;72(2);73;74;75(2);76(2);77(2);78(2);79(2);80(2);81(2);82(3);83(2);84(2);85;86;87;88;89;90(2);91;92;93(2);94(2);95(2);96(2);97;98(2);99(3);100;101;102;103(2);104;105(2);106;107(2);108(2);110;111(3);112;113;114(2);115;116;117;118;119;120;121;122;123;125(2);126(2);127;128(2);129(2);130(2);131(2);132(2);133(2);134(2);135;136;137;139(2);140;141(2);142;143;144(2);145(2);146;147(2);148(2);149;150(2);151(3);154(3);156;157(2);158;159;161(2);162;163(2);164(2);165(2);166(2);167(2);168;169;171;172;173;175;176;177(2);178;179(2);180(2);182(2);183(2);184(2);185(2);186;187(2);189(2);190(2);191(2);192(2);193(2);194(2);195;196(2);197;198(2);199;200;201(3);202(2);203(2);204(2);205;206(2);207(2);208;209(2);210;211(2);212(2);213;214(2);216;217(2);218;219(2);220(2);221;222(3);223(2);224;225(2);226(2);228;229(2);230(2);231;232(2);233(2);234(2);235;236;237(2);238;239;240;241(3);242;243;244;245(2);246;247(3);248;250(2);251;252(2);253;255(2);256;
[V] read id 10 time 44:17:74506100
[V] accumulated time 18266
[V] processing time 05:04:25:99286700

**Comment by PhilippBongartz** [comment]
Ok, I now added up the overlap length of all overlaps between two reads and sorted by overall overlap length. Those with the longest combined overlaps actually do belong to the same ground truth. So with dprime=d it seems to be working, which I just didn't realise immediately because so many local overlaps are retained. 

Is the paper already in review somewhere? I would prefer to cite it as "soon to be published in xyz" if possible. 

Thank you again for your time!

**Comment by gt1** [comment]
The paper was in the pre-proceedings of CIBB 2017 and is currently under review for the post proceedings of the conference.

**Comment by gt1** [comment]
The paper has now been accepted and will appear in some LNBI issue at some point.

**Comment by PhilippBongartz** [comment]
Congratulations and thanks for the update!
