### ISSUE TITLE
daccordcontig generate 130G core file

### ISSUE THREAD

**Issue by bitcometz** [gt1/daccord#11]
Hello, could you help with the following problem?

daccordcontig: ./DebruijnGraph.hpp:2295: void DebruijnGraph<_kmersize>::setupPreNodes(const std::pair<const unsigned char*, long unsigned int>*, uint64_t) [with unsigned int _kmersize = 6u; uint64_t = long unsigned int]: Assertion `prenodes[i-1] <= prenodes[i]' failed.
./.lsbatch/1540875918.47442.shell: line 10: 150738 Aborted                 (core dumped) daccordcontig -Ereads.eprof contigs.db reads.db sort.las > cor_contig.fa

Thanks

**Comment by gt1** [comment]
Could you provide some (preferably minimal) input data triggering this?

Thanks
German

**Comment by bitcometz** [comment]
Thanks!
I tried daccordcontig on the a genome with size of ~4Gbp and ~100x data(400Gbp) data.
Interesting, the final las file is just about 9Gbp (I am not sure weather this is normal size).

So I do not know how to provide suitable input data for you to help me solve this problem.
Or maybe I provide more log information？(log information for damapper or sort seems all ok )

The following are more log information from daccordcontig:
AlignmentStatistics(matches=737023952,mismatches=25302847,insertions=37692160,deletions=39780068,editdistance=102775075,erate=0.1223805597)
len=802106867
error estimates
erate=0.128131
cor=0.871869
ins=0.366744 0.0469914
del=0.387059 0.0495945
subst=0.246196 0.0315455
[V] using kmer range [6,8]
[V] args[0]=daccordcontig
[V] args[1]=-Ereads.eprof
[V] args[2]=contigs.db
[V] args[3]=reads.db
[V] args[4]=sort.las
[V] aread 0 windows finished 256/257697
[V] aread 0 windows finished 512/257697
...
...
[V] aread 2315 windows finished 75520/80597
[V] aread 2315 windows finished 75776/80597
daccordcontig: ./DebruijnGraph.hpp:2295: void DebruijnGraph<_kmersize>::setupPreNodes(const std::pair<const unsigned char*, long unsigned int>*, uint64_t) [with unsigned int _kmersize = 6u; uint64_t = long unsigned int]: Assertion `prenodes[i-1] <= prenodes[i]' failed.
.lsbatch/1540875918.47442.shell: line 10: 150738 Aborted                 (core dumped) daccordcontig -Ereads.eprof contigs.db reads.db sort.las > cor_contig.fa


Thanks again.

**Comment by gt1** [comment]
Hi,

daccordcontig has the J and I flags for sub-selecting input. Could you check whether your problem is indeed with read/contig id 2315? (Try running with -I2315,2315)?

**Comment by bitcometz** [comment]
Hello,

(A) I try "daccordcontig  -I2315,2315 -Ereads.eprof contigs.db reads.db sortall.las" and edited the "daccordcontig.cpp" to print out the prenodes[i-1] and prenodes[i] if (prenodes[i-1] > prenodes[i])
Then I got the above same error information and more information :
prenodes[i-1] = 253712
prenodes[i] = 243655

the length of contig_2315 is 805991.

(B) I have no problem to run daccordcontig with 40x depth data instead of 100x depth data. So 100x might be too much for daccordcontig on this 4Gbp genome?

(C) Running this contig(2315) generated ~7.9G **core** file. If I send this file to you, will it help solve this problem? I can try to upload it onto some FTP webpage.

Thanks!

**Comment by bitcometz** [comment]
Hello, an another error in the other project : 

daccordcontig: ./HandleContext.hpp:3263: void HandleContext::operator()(std::ostream&, std::ostream&, const string&, const libmaus2::dazzler::align::BinIndexDecoder&, uint64_t): Assertion `escore <= std::numeric_limits<uint32_t>::max()' failed.
/opt/gridengine/default/spool/alnode117/job_scripts/52952: line 10: 18567 Aborted                 (core dumped) daccordcontig -Ereads.eprof -t10 -d300 -D10000 contigs.db reads.db sort.las > cor_contigs.fa

Best

**Comment by gt1** [comment]
Hi,

concerning the prenodes sorting related crash, would you be able to do the following?

1. extract the relevant alignments using

```
lasproject -a2315 algn_2315.las sortall.las
```

2. extract the subset of reads required and adapted LAS file:

```
lasextract algn_2315_sub.las algn_2315_A.fasta algn_2315_B.fasta contigs.db reads.db algn_2315.las
```

3. Provide the files algn_2315_sub.las, algn_2315_A.fasta and algn_2315_B.fasta so I can reproduce the crash?

Both lasproject and lasextract can be found in lastolls (see https://gitlab.com/german.tischler/lastools)

**Comment by bitcometz** [comment]
Thanks! 

the url for the data:
https://ct.resyz.gq/download/data.tar.gz

We found daccord is much better than racon and maybe the best choice for ONT data.

Best

**Comment by gt1** [comment]
The issue is that you have regions on the contig (A-read) with more than 2^16 coverage. I'll see what I can do to handle this.

**Comment by gt1** [comment]
I have updated the code at https://gitlab.com/german.tischler/daccord . Could you check whether this fixes your first problem?

**Comment by bitcometz** [comment]
Thanks very much !!!
I will test the new version.

Best

**Comment by bitcometz** [comment]
Thanks very much !
this new version solved my problem.

Best
