### ISSUE TITLE
Too much memory consumption for daccordcontig?

### ISSUE THREAD

**Issue by bitcometz** [gt1/daccord#13]
Hello,

I run daccordcontig to do the polishing for a 4.8Gb genome with alignments from damapper.
The file size of the damapper alignment is 8.5Gb.
The following are some log information:

AlignmentStatistics(matches=21624122,mismatches=883419,insertions=1872563,deletions=618891,editdistance=3374873,erate=0.1350003470)
len=23126432
error estimates
erate=0.145931
cor=0.854069
ins=0.554854 0.0809707
del=0.183382 0.0267612
subst=0.261764 0.0381995

However, after outputing ~3Gb corrected sequences, the memory consumption of daccordcontig is up to 170G, which is 

And there are 10178 scaffolds in total, and most of them are smaller than 10k.
Is this assembly too fragmented for daccordcontig to do the polishing?
Is the 170G memory consumption normal?

Thanks!

**Comment by gt1** [comment]
Hello,

the memory consumption of daccordcontig should usually be quite moderate. A high memory consumption hints to an input LAS file with excessive depth. Could you check your file using lasdepth (from https://gitlab.com/german.tischler/lastools)? It tells you which regions on which contig are covered by home many reads.

Best,
German

**Comment by bitcometz** [comment]
Yes, you are right.
Usually, the coverage for most contigs are ~70. But for some contigs, the coverage reach more than 10000, and these contigs cause memory overflow. 
So could we use the parameter '-d: max depth' to solve this problem?

Best

**Comment by gt1** [comment]
Hi,

could you try and use laslimitdepth (see https://gitlab.com/german.tischler/lastools/blob/master/src/laslimitdepth.cpp) to reduce the depth in the input file? Try

laslimitdepth -d200 filtered.las contigs.db input.las

The -d flag in daccordcontig does not help for this purpose.

**Comment by bitcometz** [comment]
Thanks for your help！
I try this program and it works!

Best
