### ISSUE TITLE
Update source to be compatible with newest libmaus2?

### ISSUE THREAD

**Issue by olekto** [gt1/daccord#16]
Hi,
I'm trying to install d'accord because I want to try dentist (https://github.com/a-ludi/dentist). However, this was a bit complicated. It seems that the classes and functions d'accord calls from libmaus2 is not present in the most recent releases. I'm trying release 2.0.631 of libmaus2 to see if that works. Are you planning to update d'accord? If not, could you specify which release of libmaus2 which is compatible with d'accord?

Thank you.

Sincerely,
Ole

**Comment by gt1** [comment]
Hi,

could you check the latest code on https://gitlab.com/german.tischler/daccord ? Make sure you also use libmaus2 code from gitlab.

Best,
German

**Comment by olekto** [comment]
Thank you. By checking out the latest code on both of these repositories, d'accord did compile just fine.

Ole
