### ISSUE TITLE
problem of .las file 

### ISSUE THREAD

**Issue by LeoChanW** [gt1/daccord#2]
Hi ! 
  I have installed Daligner(https://github.com/thegenemyers/DALIGNER), but I do not find how to get .las file.  Should I get .las by DAMAPPER?

**Comment by gt1** [comment]
You first need to create a Dazzler database (assuming your reads are in reads.fasta):

fasta2DB reads.db reads.fasta
DBsplit -s192 -x1000 reads.db

fasta2DB and DBsplit are in the DAZZ_DB package (see https://github.com/thegenemyers/DAZZ_DB).

Then run DALIGNER on the database file with

HPC.daligner reads.db | bash

These steps require you to have the DAZZ_DB and DALIGNER programs in accessible via your PATH variable (i.e. you need to be able to run them without providing the full path of the binaries). DALIGNER has more options not shown here, please see the project page for what they are.

**Comment by LeoChanW** [comment]
Hi ! When I run daccord，there are some problems.
(gmp library has installed by yum).
_____________________________________________________________________________________________
libmaus2::math::GmpFloat(): library is not built with gmp support
/home/chw/libmaus2/lib/libmaus2.so.2(libmaus2::util::StackTrace::StackTrace()+0x54)[0x7f1badeea924]
/home/chw/libmaus2/lib/libmaus2.so.2(libmaus2::math::GmpFloat::GmpFloat(double, unsigned int)+0x36)[0x7f1badf7e726]
daccord(computeOffsetLikely(unsigned long, double, double)+0x21e)[0x42cb1e]
daccord(daccord(libmaus2::util::ArgParser const&, std::string const&, std::string const&, std::string const&)+0x1fc2)[0x436c92]
daccord(main+0x126d)[0x4283dd]
/lib64/libc.so.6(__libc_start_main+0xf5)[0x7f1bac3bcb35]
daccord()[0x428c81]

**Comment by gt1** [comment]
Hi,

sorry, this should be in the documentation. You need to use

--with-gmp

when configuring libmaus2 before building it.

**Comment by LeoChanW** [comment]
Daccord can run normally.
Thanks for your help and patience！
