### ISSUE TITLE
RUN checklas: in.las is not sorted

### ISSUE THREAD

**Issue by svm-zhang** [gt1/daccord#4]
Hello @gt1 ,

I used minialign to align my reads against a reference, and a SAM file was generated. Below gives what I did to get from the SAM to LAS file.

bamsormadup <reads.sam >reads.bam
bamrecalculatecigar reference=ref.fasta <reads.bam >reads.eqdiff.bam
bamtolas test.las reads.fasta <reads.eqdiff.bam

I then ran:

checklas reads.db genperfect.las in.bam test.las

And I got the error as shown in this [checklas.txt](https://github.com/gt1/daccord/files/1291443/checklas.txt). The test.S.las file is what I tried with LAsort on test.las.

Could you please give some insights where I did wrong here? Thanks for any help!

Simo

**Comment by gt1** [comment]
Hello,

you will need to use lassort in lastools to sort the input file(s). It produces a stricter sorting than daligner's LAsort.

Using checklas to check files produced by bamtolas however may be a bit more tricky than using it for daligner based output. checklas compares alignments using their trace point representation (see https://dazzlerblog.wordpress.com/2015/11/05/trace-points/). The problem now is that bamtolas by default uses a trace point spacing of 126 (this allows for more alignments, especially with very bad regions, something which daligner would not produce, but some others do) and generateperfectpiles has a default of 100, so files produced using these default cannot be compared. The newest version of checklas (updated today) checks this, previous ones just report non-sense. You need to call generateperfectpiles using --tspace126 to obtain a file suitable for using checklas with anything produced by bamtolas.

Best,
German

**Comment by svm-zhang** [comment]
Hello @gt1,

It worked! Thanks very much for pointing out. Could you give a quick explanation of what you meant by "stricter sorting"? I am curious and I'd like to try to understand :)

And thanks very much for letting me know the trace point spacing problem. For alignments generated by daligner/damapper, if I use -s1000 as my trace point spacing in my command line, do I need to make sure running generateperfectpiles using --tspace1000?

Thanks for your help!
Simo

**Comment by gt1** [comment]
Hello @svm-zhang,

as your file checklas.txt states, your input file has (0,592) after (0,1192) for (aread,bread) pairs. lassort produces a lexicographic sorting here where (0,592) appears before (0,1192).

The comparison by trace points in checklas is somewhat coarse. It may miss things at a trace point spacing of 1000. Note that using a spacing of 1000 may save you a little space, but it slows down the recovery of alignments (you need to solve 1000x1000 alignments instead of 100x100 to recover the original full alignment). If your aim is using checklas, then I would suggest reducing the trace point spacing to a smaller value. checklas could be rewritten to use exact alignments instead of just trace points, but that would make it a lot slower.

Best,
German

**Comment by svm-zhang** [comment]
Hello @gt1, that makes a lot of sense. Thanks for clarifying it out for me.

I do have one following question about the evaluation results I got from checklas. Let me show two reads from the checklas output.

`[R] 16 missing 2289 got 186 extra 939 erate 0.198378 NC_001224.1:171116,185631 0.924848 0 0 0 669 regular`
`[R] 17 missing 1353 got 0 extra 0 erate 0.190931 NC_001224.1:99719,106156 1 0 0 0 0 complete miss`

If you look at my DAMAPPER results for these two reads in the LAS file (LAshow):

` 1       17 n   [  171,116..  174,574] x <     0.. 3,516]  ~  16.8%   (   587 diffs,  28 trace pts)`
` 1       17 n   [  174,715..  181,130] x [ 3,667..10,295]  ~  17.0%   ( 1,108 diffs,  52 trace pts)`
` 1       17 n   [  181,287..  181,531] x [10,452..10,704]  ~  15.7%   (    39 diffs,   3 trace pts)`
` 1       17 n   [  181,663..  184,291] x [10,842..13,526]  ~  17.2%   (   456 diffs,  22 trace pts)`
` 1       17 n   [  184,474..  185,632] x [13,725..14,905>  ~  15.4%   (   180 diffs,  10 trace pts)`
` 1       18 c   [  186,640..  192,448] x < 5,842..     0>  ~  15.5%   (   901 diffs,  47 trace pts)`

I simulated these reads using PBSIM, and so the ground truth in the BAM file are (only first 4 fields shown):

`S1_17/16/0_14905        0       NC_001224.1     171117 `
`S1_18/17/0_5842 16      NC_001224.1     186640`

As you can see that both the alignments are really good, though read 17 is broken up into multiple chains.

My first question is for read 18 (index 17 in the evaluation result), why checklas thinks it is missing?

Second question, for read 17 (index 16 in the evaluation result), how can I interpret the result? Ground truth alignments missing and present in the DAMAPPER LAS result are 2289 and 189, so the 2289 trace points missing?

So I tried to go deep myself a bit, and I tried to look at the perfect pile (LAshow the perfecttile.las file), and found the following:

` 1       17 n   <        0..    6,827] x [ 8,025..14,905>  ~  37.7%   ( 2,585 diffs,  69 trace pts)`
` 1       18 c   [    7,849..    8,087] x < 5,842.. 5,591]  ~  36.0%   (    88 diffs,   3 trace pts)`

Apparently some info are missing in here, which might cause what we see above? Any idea?

Thanks again,
Simo

**Comment by gt1** [comment]
Hello @svg-zhang,

could you upload the files somewhere, so I could have closer look?

Thanks
German

**Comment by svm-zhang** [comment]
Hello @gt1,

I can share you with the LAS file for perfect pile, the simulated BAM, and the LAS file converted from the simulated BAM. The whole tarball is about 9GB. I have finished uploading to my google drive. Could you please give me your google account ?

Thanks,
Simo

**Comment by gt1** [comment]
Hello @svm-zhang,

I have downloaded the data you shared with me. I hope I'll get around and have a closer look soon.

Thanks
German

**Comment by svm-zhang** [comment]
Hello @gt1 ,

Thanks very much, and please keep me posted.

Simo

**Comment by gt1** [comment]
Hello @svm-zhang ,

there seems to be something wrong with your BAM file. There is

```
@SQ     SN:NC_001224.1  LN:85779
```

but

```
S1_1/0/0_8087   0       NC_001224.1     178939
```
i.e. an alignment starting at position 178939 on a sequence of 85779. There are only alignments for NC_001224.1 in the file, so I guess something went wrong with the BAM file generation.

German

**Comment by gt1** [comment]
Hello @svm-zhang ,

if you are using maftobam, then it may be necessary to produce the alignments separately for each chromosome and then merge the resulting BAM files.

German

**Comment by svm-zhang** [comment]
Hello @gt1,

Thanks pointing out! It is wrong. I think it was because something I changed in the pbsim.cpp. I didn't expect to I messed up this part, as all I did was trying to make pbsim stop reading ref ids at first sight of spaces...

I am re-running pbsim (https://github.com/ocxtal/pbsim/tree/nfree) without modifying anything. I will update my result soon. Thanks again for the help.

Simo

**Comment by svm-zhang** [comment]
Hello @gt1,

I think I still see the same problem. But let me first show you what I did.

```
pbsim $(cat pbsim.cfg) ref.fasta

ls *.maf | sed 's/\.maf//g' | xargs -n1 -t -I{} bash -c "maftobam ref.fasta <{}.maf >{}.bam || exit 255"

samtools cat -b $(ls *.bam) -o all.bam

bamidreanme <all.bam >all.rename.bam

bamsormadup threads=4 indexfilename=all.rename.bam.bai <all.rename.bam >all.rename.cso.bam

generateperfectpiles -tspace126 all.rename.cso.perfect.las all.rename.cso.bam

samtools fasta all.rename.bam >reads.fasta

call.damapper ref.fasta <reads.fasta >reads.bam

bamtolas reads.las reads.fasta <reads.bam

lassort reads.S.las reads.las

fasta2DB -v reads reads.fasta

DBsplit -s250 -x500 reads.db

checklas reads.db all.rename.cso.perfect.las all.rename.bam reads.S.las
```

I still see read id 17 is marked as complete missing in the checklas report, while in the LAshow read id 17 is clearly mapped. In the `all.rename.cso.perfect.las` file, read id 17 only has the same info as shown in my earlier post above. I tried to run `LAshow` on the `all.rename.cso.perfect.las`, and got an seg fault error. So my guess is that I did something wrong with `generateperfectpiles`?

I can share you with newly produced `all.rename.cso.bam` (ground truth bam), and `reads.bam` (damapper results in BAM), if you need them.

Thanks again for your help!

Simo

**Comment by gt1** [comment]
Hello @svm-zhang ,

I think I misunderstood your objective, apologies for that. checklas is a program for checking read against read, not read against reference alignments. Analogously generateperfectpiles generates alignments between the reads in a BAM file, not between a read and the reference it is mapped to.

I have 

https://github.com/gt1/loresim2/blob/master/src/mapcheckstrict.cpp

for comparing read to reference alignment files.

This is run by

```
mapcheckstrict groundtruth.bam alignerproduced.bam
```

where both input files need to be sorted by query name.

German

**Comment by svm-zhang** [comment]
Hello @gt1 ,

Ah, I see. `checklas` is used checking for read-vs-read overlaps. Good to know. I have data on this, and I can try right away. Thanks for clarifying. I will use the loresim2 repo and update you soon. 

btw, is it possible you could give a bit more description on how the error models behind `longreadsim`? And what types of output I should be expecting from it? I am considering to use it as a replacement for pbsim.

Simo

**Comment by svm-zhang** [comment]
Hello @gt1 ,

I did a quick test on `mapcheckstrict`, and both `groundtruth.bam` and `damapper.bam` are sorted by queryname. I got an segmentation fault. Any idea what could go wrong?

Simo

**Comment by gt1** [comment]
Hello @svm-zhang ,

thank you for trying mapcheckstrict. Could you provide me with a short prefix of the two BAM files sufficient to trigger a segmentation fault?

I should write a bit more documentation for longreadgen . Essentially it uses a simple two state model where the two states represent low (~15% by default) and high (25% by default) error rate intervals on reads. For each read and error interval on the read a number of errors is computed using a Gaussian distribution around these center points (15% or 25%) and that number of errors is inserted. The proportion of insertions, deletions and substitutions can be given as a parameter (by default these are 50% insertions, 30% deletions and 20% substitutions). The read lengths produced follow a log normal distribution with given parameters (parameter names are readlenavg and readlenstddev). The defaults for these are avg 8.5k and 6.9k .

Thanks
German

**Comment by svm-zhang** [comment]
Hello @gt1,

I just shared the first 100 alignments in both truth and result BAM files via google drive. Please let me know if you don't get it. These were generated using:

```
samtools view -h results.so.bam | awk '(NR<=122)' | samtools view -bh - > results.100.so.bam
samtools view -h truth.so.bam | awk '(NR<=121)' | samtools view -bh - > truth.100.so.bam
```
There are 22 and 21 header lines in the results and truth BAM files, respectively.

And thanks very much for the details for the error and read models. I already tried yesterday and it worked like charms, and saved me from tedious name and format conversion, etc. May I follow up with some questions:

1. Given a read and an error interval on it, are errors inserted randomly?
2. Given a read, how are error intervals selected? To decide whether a low or high interval, what distribution used?

Thanks,
Simo

**Comment by gt1** [comment]
Hello @svm-zhang ,

I have updared mapcheckstrict so I should not fail on your files. The previous version required tags set by loresim2's longreadgen.

Concerning your other questions:
1. Yes, errors inside those intervals are inserted randomly (concerning both type and position).
2. Interval selection follows a two state finite state machine controlled by the parameters eratelow (average error rate for low state), eratelowstddev (standard deviation for low state, actual error rate follows a normal distribution), eratehigh/eratehighstddev (same for high state), startlowprob (probability to start in low state), keeplowstate (probability to stay in low state for another base), keephighstate (same for high state, argument parsing looks broken, I need to fix this).

Best,
German

**Comment by svm-zhang** [comment]
Hello @gt1,

Thanks for fixing it. It worked for me now. Do you have a description on the output?

```
[S] skip_a=0
[S] skip_b=0
[S] unmapped=0
[S] g_anycross=47
[S] g_nocross=0
[S] g_anyoverlap=47
[S] g_nooverlap=0
[S] g_primaryanycross=47
[S] g_primarynocross=0
[S] g_primaryanyoverlap=47
[S] g_primarynooverlap=0
[S] read overlap fraction=0.970913
[S] read cross fraction=0.970913
[S] ref overlap fraction=0.971498
[S] ref cross fraction=0.971498
[S] primary read overlap fraction=0.970913
[S] primary read cross fraction=0.970913
[S] primary ref overlap fraction=0.971498
[S] primary ref cross fraction=0.971498
[S] mdiam avg 0.971925
[S] mdiam sum avg 0.970913
```

And thanks for answering my model questions. They are clear to me now.

Simo

**Comment by gt1** [comment]
Hello @svm-zhang ,

there is

* skip_a : reads found in first input file but not in second
* skip_b: vice versa
* unmapped: reads found in mapped file, but marked as unmapped

For the next fields there is

* cross: a mapped read is aligned in the same way as the ground truth for at least one base
* overlap: the mapping intervals overlap with the ground truth mapping for at least one mapping
* primary: at least one of the alignments in case is not marked with the secondary flag (this is to check whether the aligner marks the true alignment as the primary in case it produces more than one alignment for a read)

Overlap and cross fractions are similar but count single bases instead of reads .

mdiam avg is the average mapped bases over the reads (i.e. compute fraction of mapped bases for each read, then average this over all reads)
mdiam sum avg is the number of mapped bases summed over all reads divided by the number of all read bases.

You can get a more precise output using the flag -V1 .

German

**Comment by svm-zhang** [comment]
Hello @gt1,

Thanks for these details. They are very helpful, as well as the output I got from -V1. I am closing it now. If I have more problems with `checklas` I will open a new issue. Thanks again.

Simo
