### ISSUE TITLE
is it ok for daccord to run with the las generated from the falcon pipeline?

### ISSUE THREAD

**Issue by bitcometz** [gt1/daccord#5]
I have try to used the latest falcon pipeline to generate las file and run with daccord, but it failed.
Is it because that the daligner in falcon pipeline has been altered ？

Thanks

**Comment by gt1** [comment]
It should work as long as the file format remains the same. Can you provide some error message you see?

**Comment by bitcometz** [comment]
Thanks！
In falcon I first:
while read fn; do  cat  $fn | fasta2DB -v raw_reads -i${fn##*/}; done < input.fofn
DBsplit -a -x6000 -s50 raw_reads
DBdust raw_reads

Then run : HPC.TANmask -P.  -v -ftan-jobs raw_reads to mask some repeat region
Then run : HPC.daligner -P. -v -B30 -e.75 -k16 -h300 -l2500 -w8 -H1000 -T8 -s1000 -M35 -t30 -H8000 -mdust -mtan -fdaligner-jobs ./raw_reads to generate all the daligner shells and get the las file.


Then I try the las file of ecoli data from Falcon, and daccord continue to output the following information without stopping(at least 72 hours):
[V] args[0]=~/bin/daccord
[V] args[1]=raw_reads.1.las
[V] args[2]=raw_data.dam
[V] copying .raw_reads.1.las.bidx to mem:.input.las.bidx...done.
[V] copying .raw_reads.1.las.idx to mem:.input.las.idx...done.
[V] minaread=0 toparead=3628
[V] minfilterfreq=0 maxfilterfreq=2
[V] copying raw_data.dam to memory...done.
[S] handling aread 0 depth 138
[S] handling aread 4 depth 174
[S] handling aread 30 depth 276
[S] handling aread 13 depth 275
[S] handling aread 26 depth 307
[S] handling aread 36 depth 63
[S] handling aread 8 depth 78
.......

And I try the command with the same data : 
HPC.daligner reads.dam | bash to generated me three .las files and run daccord again.
Then I soon(a few minutes) get the results (*.fasta) with the following information:
[V] args[0]=~/bin/daccord
[V] args[1]=reads.las
[V] args[2]=reads.dam
[V] copying .reads.las.bidx to mem:.input.las.bidx...done.
[V] copying .reads.las.idx to mem:.input.las.idx...done.
[V] minaread=0 toparead=31298
[V] minfilterfreq=0 maxfilterfreq=2
[V] copying reads.dam to memory...done.
AlignmentStatistics(matches=607565197,mismatches=9256862,insertions=56085761,deletions=27091603,editdistance=92434226,erate=0.1320490031)
len=643913662
error estimates
erate=0.143551
cor=0.856449
ins=0.606764 0.0871014
del=0.293091 0.0420733
subst=0.100145 0.0143759
cor^8=0.289477
[V] using kmer range [8,8]
[V] graph structures set up
[S] handling aread 0 depth 670
[V] read id 0 time 44:71869399
[S] handling aread 1 depth 119
[V] read id 1 time 37:38264199
[S] handling aread 2 depth 122
[V] read id 2 time 39:43883399
[S] handling aread 3 depth 26

**Comment by gt1** [comment]
I have never used a trace point spacing of 1000 (-s switch for daligner), daligner default is 10 times smaller. This may not be practical for daccord. I wonder whether falcon ever decodes these overlaps, it would be pretty slow.

**Comment by bitcometz** [comment]
Thanks very much! It works now!
