### ISSUE TITLE
is daccord suitable for error correction of scaffolds?

### ISSUE THREAD

**Issue by bitcometz** [gt1/daccord#7]
Hello,

If I used minimap2+miniasm to generate a draft genome without error correction, is it ok that
I use DAMAPPER to map ONT reads to the a draft genome to generate *.las file and I use daccord to do the error correction of the draft genome sequence?

Thanks

**Comment by gt1** [comment]
Hello,

I would suggest to use daccordcontig (see https://gitlab.com/german.tischler/daccord/blob/master/src/daccordcontig.cpp) for this. You will need to sort the LAS file produced by damapper using lassort in https://gitlab.com/german.tischler/lastools with sort order aidapos and given the contigs DB as -d option while sorting to produce an index for that sorted LAS file.

**Comment by bitcometz** [comment]
Thanks!
I try the following command:

fasta2DB contigs assembl.fasta
fasta2DB reads subreads.fasta
DBsplit -x20 -s250 contigs
DBsplit -x0 -s250 reads
HPC.damapper -C -N -k20 contigs.db reads.db | grep "^damapper" |bash
lassort -saidapos -dcontigs.db sort.las contigs.reads.1.las contigs.reads.2.las ...
daccordcontig contigs.db reads.db sort.las

Then I got the error information:
error output:
[V] unable to find eprof file sort.las.eprof

I know daccord can generate the file
So I tried to run daccord: 
daccord sort.las contigs.db, but error occurred as shown below:

[V] args[0]=daccord
[V] args[1]=sort.las
[V] args[2]=contigs.db
file sort.las is not sorted

Thanks!

**Comment by gt1** [comment]
You need compute an .eprof (error profile) file characterising the error model expected by a run of daccord on raw read data. You can use the --eprofonly option for this.

**Comment by bitcometz** [comment]
Thanks!
Oh, I thinks it will consume a lot of time to generate *.eprof file with daccord since it will require the all vs all alignments between reads with daligner? Am I right?

**Comment by gt1** [comment]
daccord computes the eprof file using alignments for the first 1000 reads in a database by default, so you do not need all vs all alignments, 1000 reads against all will suffice. You can also use an eprof file computed for a different dataset if the sequencing parameters are the same.

**Comment by bitcometz** [comment]
great！

**Comment by bitcometz** [comment]
hello, I tried to use the daccordcontig to polish the assembled scaffolds from wtdgb2 based on ONT reads and got unexpected unsatisfactory result:

A) BUSCOs assessment for the initial scaffolds from wtdbg2:
C:87.3%[S:85.6%,D:1.7%],F:3.9%,M:8.8%,n:1440

B) BUSCOs assessment for scaffolds after daccordcontig
C:70.9%[S:69.4%,D:1.5%],F:6.7%,M:22.4%,n:1440

As far as I am concerned, the high error rate of scaffolds sequences will reduce the evaluation index.
It would be great if you could offer some advice on this issue. Thanks!

**Comment by gt1** [comment]
I am not sure what is going on there. Would you be able to provide some sample data?

**Comment by bitcometz** [comment]
Thanks for you help! 
I will check my results carefully first. Hopefully doing this could help solve this problem.

**Comment by bitcometz** [comment]
Hello, I tested daccord again and it really generated good results, Thanks ^_^
