### ISSUE TITLE
Installation difficulties

### ISSUE THREAD

**Issue by PhilippBongartz** [gt1/daccord#8]
Hi,

I'm currently trying to install Daccord on my mac, which results in the error message:

configure: error: Package requirements (libmaus2 >= 2.0.352) were not met:
No package 'libmaus2' found

So, I tried to reinstall libmaus2, now also using the flag --with-gmp. Make now ran forever and make check produces:

Making check in src
make[1]: Nothing to be done for `check'.
Making check in test
/Applications/Xcode.app/Contents/Developer/usr/bin/make check-TESTS
/bin/sh: ../test-driver: No such file or directory
make[3]: *** [testAIO.sh.log] Error 127
make[2]: *** [check-TESTS] Error 2
make[1]: *** [check-am] Error 2
make: *** [check-recursive] Error 1

I proceeded with the installation anyway and then tried
./configure --with-libmaus2=/usr/local/lib --prefix=${HOME}/daccord
in the daccord-master file. Which again resulted in No package 'libmaus2' found.

Would be great if you could give me some pointers how to install this correctly.

**Comment by gt1** [comment]
Please try running configure as

./configure --with-libmaus2=/usr/local --prefix=${HOME}/daccord

assuming you used /usr/local as prefix when running configure for libmaus2.

**Comment by PhilippBongartz** [comment]
Ah, I had only tried /usr/local/bin or maybe /usr/local/lib or something. But now there is actually a new kind of error, so there is progress! 

checking for libmaus2 >= 2.0.352... yes
checking whether we can compile a program using libmaus2... yes
checking whether libmaus2 was compiled with support for the GMP library... no
configure: error: Required GMP support in libmaus2 is not available.

I did use ./configure --with-gmp --prefix=/usr/local
But I kind of assume that with my nonexistent computer knowledge, I messed up some path stuff in the relationship of gmp and libmaus2. 

Is there anything specific I should have done when installing gmp? Or can I somehow more specifically tell libmaus2 where to find gmp?

**Comment by gt1** [comment]
You need to have the line

```
checking whether we can compile a program using the gmp library... yes
```

in the output of configure for libmaus2. The --with-gmp flag is fine if you have the gmp library somewhere in the default path, otherwise you need to install it first and provide --with-gmp=/usr/local (or wherever you installed it). You can find the source for gmp at https://gmplib.org .

**Comment by PhilippBongartz** [comment]
Ok, thank you so much. Now it seems to be working. I'll probably be back with a load of questions once I've slogged my way through getting dazz-db and daligner to do what they are supposed to.

**Comment by ddrazoh** [comment]
hello, i have tried following the conversation but failed. Kindly help me with the step by step code to instal daccord on mac. Thanks
