### ISSUE TITLE
Segmentation fault

### ISSUE THREAD

**Issue by PhilippBongartz** [gt1/daccord#9]
So I managed to turn my fasta file into a .db. and to calculate all overlaps. 

Now when I try to run ./daccord -t4 -D500 Reads.las Reads.db

[V] args[0]=./daccord
[V] args[1]=-t4
[V] args[2]=-D500
[V] args[3]=Reads.las
[V] args[4]=Reads.db
[V] copying Reads.las.bidx to mem:.input.las.bidx...done.
[V] copying Reads.las.idx to mem:.input.las.idx...done.
[V] minaread=0 toparead=14577
[V] minfilterfreq=0 maxfilterfreq=2
[V] copying Reads.db to memory...done.
[V] loading and trimming Reads.db...done.
[V] setting up read decoder allocators...done.
[S] handling aread 0 depth 500
[S] handling aread 1 depth 9
[S] handling aread 2 depth 500
[S] handling aread 3 depth 500
[S] handling aread 4 depth 500
...
[S] handling aread 1020 depth 500
[S] handling aread 1021 depth 500
[S] handling aread 1022 depth 500
[S] handling aread 1023 depth 500
usable=737783 unusable=1503244 eavg=0.131651 edif=0.0031995
AlignmentStatistics(matches=963715553,mismatches=21527156,insertions=101821194,deletions=24578887,editdistance=147927237,erate=0.1330708374)
len=1009821596
error estimates
erate=0.146488
cor=0.853512
ins=0.688319 0.100831
del=0.166155 0.0243398
subst=0.145525 0.0213178
cor^8=0.281628
[V] using kmer range [8,8]
[V] creating KmerLimit for k=8...done.
[V] graph structures set up MemUsage(size=2617.1,rss=183.137,peak=0)
Segmentation fault: 11

When I run it again, I get the statistics and the segfault immediately. It also doesn't seem to run on four threads. Any help would be appreciated. 

Another thing: Reads.las etc is edited by me to avoid a pretty long path. So in reality data and tool are not in the same file. Maybe relevant, probably not.

**Comment by gt1** [comment]
Could you check whether you see the same with the more recent code at gitlab (https://gitlab.com/german.tischler/daccord)? This will also require to the gitlab version of libmaus2.

**Comment by PhilippBongartz** [comment]
Now I downloaded and installed the newest gitlab release version of libmaus2 and daccord.
It seems to be working now, it is busily spitting out reads. Still no sign though that it is running on four cores, I think there was even a warning about pthread at some compilation step?

Anyway, that is a minor issue, I really appreciate your quick and helpful response.

**Comment by gt1** [comment]
The parallelism in daccord is based on OpenMP, which the clang compiler shipped with apples Xcode environment does not support. You can use homebrew (https://brew.sh/index_de) to install a suitable version of GCC to get parallelism on MacOS (well that's what I do).

**Comment by PhilippBongartz** [comment]
Ok, I think that isn't necessary for my project. The prohibitively expensive step seems to be the splitting and that can be "parallelised" by hand. 

I try to do a comparison between my repeat resolving stuff and your daccord based stuff. My method is specialised on high copy numbers. I assume your algorithms aren't really made for repeat families with a hundred copies, but the editors and reviewers apparently need to see some kind of comparison with existing methods and yours seems to be the only dedicated repeat resolving method for long reads. 

Do you have any tips how to get the best performance out of your tools for high copy numbers? Or is there a hard limit beyond which it doesn't really make sense? And finally, are your two papers already in review somewhere?
